const comments = {
    COMMENTS_COMMENT_REQUEST: 'COMMENTS_COMMENT_REQUEST',
    COMMENTS_COMMENT_SUCCESS: 'COMMENTS_COMMENT_SUCCESS',
    COMMENTS_COMMENT_FAILURE: 'COMMENTS_COMMENT_FAILURE'
}

export { comments }
