const comments = {
    COMMENTS_COMMENT_REQUEST: 'COMMENTS_COMMENT_REQUEST',
    COMMENTS_COMMENT_SUCCESS: 'COMMENTS_COMMENT_SUCCESS',
    COMMENTS_COMMENT_FAILURE: 'COMMENTS_COMMENT_FAILURE',

    COMMENTS_SET_RECIPE_ID: 'COMMENTS_SET_RECIPE_ID'
}

export { comments }
