const recipe = {
    RECIPE_SAVE_REQUEST: 'RECIPE_SAVE_REQUEST',
    RECIPE_SAVE_SUCCESS: 'RECIPE_SAVE_SUCCESS',
    RECIPE_SAVE_FAILURE: 'RECIPE_SAVE_FAILURE',

    RECIPE_LOAD_REQUEST: 'RECIPE_LOAD_REQUEST',
    RECIPE_LOAD_SUCCESS: 'RECIPE_LOAD_SUCCESS',
    RECIPE_LOAD_FAILURE: 'RECIPE_LOAD_FAILURE',

    RECIPE_PUBLISH_REQUEST: 'RECIPE_PUBLISH_REQUEST',
    RECIPE_PUBLISH_SUCCESS: 'RECIPE_PUBLISH_SUCCESS',
    RECIPE_PUBLISH_FAILURE: 'RECIPE_PUBLISH_FAILURE',

    RECIPE_UNPUBLISH_REQUEST: 'RECIPE_UNPUBLISH_REQUEST',
    RECIPE_UNPUBLISH_SUCCESS: 'RECIPE_UNPUBLISH_SUCCESS',
    RECIPE_UNPUBLISH_FAILURE: 'RECIPE_UNPUBLISH_FAILURE'
}

export { recipe }
