const recipe = {
    RECIPE_SAVE_REQUEST: 'RECIPE_SAVE_REQUEST',
    RECIPE_SAVE_SUCCESS: 'RECIPE_SAVE_SUCCESS',
    RECIPE_SAVE_FAILURE: 'RECIPE_SAVE_FAILURE',

    RECIPE_EDIT_REQUEST: 'RECIPE_EDIT_REQUEST',
    RECIPE_EDIT_SUCCESS: 'RECIPE_EDIT_SUCCESS',
    RECIPE_EDIT_FAILURE: 'RECIPE_EDIT_FAILURE',

    RECIPE_PUBLISH_REQUEST: 'RECIPE_PUBLISH_REQUEST',
    RECIPE_PUBLISH_SUCCESS: 'RECIPE_PUBLISH_SUCCESS',
    RECIPE_PUBLISH_FAILURE: 'RECIPE_PUBLISH_FAILURE',

    RECIPE_UNPUBLISH_REQUEST: 'RECIPE_TOGGLE_PUBLISHED_REQUEST',
    RECIPE_TOGGLE_PUBLISHED_SUCCESS: 'RECIPE_TOGGLE_PUBLISHED_SUCCESS',
    RECIPE_TOGGLE_PUBLISHED_FAILURE: 'RECIPE_TOGGLE_PUBLISHED_FAILURE',

    RECIPE_UPDATE_REQUEST: 'RECIPE_UPDATE_REQUEST',
    RECIPE_UPDATE_SUCCESS: 'RECIPE_UPDATE_SUCCESS',
    RECIPE_UPDATE_FAILURE: 'RECIPE_UPDATE_FAILURE',

    RECIPE_LOAD_REQUEST: 'RECIPE_LOAD_REQUEST',
    RECIPE_LOAD_SUCCESS: 'RECIPE_LOAD_SUCCESS',
    RECIPE_LOAD_FAILURE: 'RECIPE_LOAD_FAILURE',

    RECIPE_RECENT_REQUEST: 'RECIPE_RECENT_REQUEST',
    RECIPE_RECENT_SUCCESS: 'RECIPE_RECENT_SUCCESS',
    RECIPE_RECENT_FAILURE: 'RECIPE_RECENT_FAILURE',

    RECIPE_TOP_REQUEST: 'RECIPE_TOP_REQUEST',
    RECIPE_TOP_SUCCESS: 'RECIPE_TOP_SUCCESS',
    RECIPE_TOP_FAILURE: 'RECIPE_TOP_FAILURE',

    RECIPE_LIKE_REQUEST: 'RECIPE_LIKE_REQUEST',
    RECIPE_LIKE_SUCCESS: 'RECIPE_LIKE_SUCCESS',
    RECIPE_LIKE_FAILURE: 'RECIPE_LIKE_FAILURE',

    RECIPE_UNLIKE_REQUEST: 'RECIPE_UNLIKE_REQUEST',
    RECIPE_UNLIKE_SUCCESS: 'RECIPE_UNLIKE_SUCCESS',
    RECIPE_UNLIKE_FAILURE: 'RECIPE_UNLIKE_FAILURE',

    RECIPE_REPORT_REQUEST: 'RECIPE_REPORT_REQUEST',
    RECIPE_REPORT_SUCCESS: 'RECIPE_REPORT_SUCCESS',
    RECIPE_REPORT_FAILURE: 'RECIPE_REPORT_FAILURE',

    RECIPE_SEARCH_REQUEST: 'RECIPE_SEARCH_REQUEST',
    RECIPE_SEARCH_SUCCESS: 'RECIPE_SEARCH_SUCCESS',
    RECIPE_SEARCH_FAILURE: 'RECIPE_SEARCH_FAILURE'
}

export { recipe }
