const user = {
    USER_REGISTER_REQUEST: 'USER_USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_USER_REGISTER_FAILURE',

    USER_LOGIN_REQUEST: 'USER_USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: 'USER_USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE: 'USER_USER_LOGIN_FAILURE',

    USER_LOGOUT_REQUEST: 'USERS_USER_LOGOUT_REQUEST',
    USER_LOGOUT_SUCCESS: 'USERS_LOGOUT_SUCESS',

    USER_LOAD_PROFILE_REQUEST: 'USERS_USER_LOAD_PROFILE_REQUEST',
    USER_LOAD_PROFILE_SUCCESS: 'USERS_USER_LOAD_PROFILE_SUCCESS',
    USER_LOAD_PROFILE_FAILURE: 'USERS_USER_LOAD_PROFILE_FAILURE'
}

export { user }
