const user = {
    REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    LOGOUT_REQUEST: 'USERS_LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'USERS_LOGOUT_SUCESS',

    LOAD_PROFILE_REQUEST: 'USERS_LOAD_PROFILE_REQUEST',
    LOAD_PROFILE_SUCCESS: 'USERS_LOAD_PROFILE_SUCCESS',
    LOAD_PROFILE_FAILURE: 'USERS_LOAD_PROFILE_FAILURE'
}

export { user }
